### ISSUE TITLE
Game Never Starts

### ISSUE THREAD

**Issue by KXIIIS** [anhcraft/honeymod#1]
Hey, I really want to use your mod but when I start MC through the launcher, the game never starts and when I click on the play button again, I get this message.

![Snip20200426_2](https://user-images.githubusercontent.com/62857357/80316787-c87e7e80-87cd-11ea-902c-4531bd247429.png)

 It doesn't crash so I don't have a crash report but I'm on:
[Fabric 0.8.2+build.194-1.15.2] 
[Fabric API 0.7.1. build 301] 
[honeymod-1.0.2-1.15.2]

**Comment by anhcraft** [comment]
@KXIIIS
Hello,
I just tested again (HoneyMod v1.0.2, MC 1.15.2). It seems everything is working fine for me.
About the error from your image, it said "the game already running", it means you are running multiple Minecraft at the same time, it is nothing related to mod (even others).
--------------------------------------
However, I'd like to get more details, just make sure this mod is working fine.
In your launcher, go to Settings, in the General tab, tick the box "Open output log when the game starts".
When you run Minecraft, you will see a console, it lists all logs in the game (and yes, including any errors). If it mentioned HoneyMod, you can capture the screen and send me the link.
Thanks

**Comment by KXIIIS** [comment]
Hello. Yes, I'm aware the image I provided doesn't directly have anything to do with mods but there's something that's preventing the game from starting and I'm not quite sure what it is. I've done what you've asked and I did see the HoneyMod name but I don't know what and if it means anything. 

![Snip20200427_1](https://user-images.githubusercontent.com/62857357/80393042-f3c0a680-887d-11ea-826a-9f4ff6bd0810.png)

**Comment by anhcraft** [comment]
@KXIIIS
Yeah, the image you provided had no errors at all. Can you give me the full logs?
Simply Ctrl + A and paste to hastebin or pastebin

**Comment by KXIIIS** [comment]
https://pastebin.com/rFtDUYnx

Sorry if it's messy, I've never used pastebin before. 
That is the full log. The game never goes past that stage.

**Comment by anhcraft** [comment]
Hmm, I couldn't find anything from that logs...
Can I ask a few questions?
- Can you run Minecraft 1.15.2 without mods?
- If you remove this mod, can you run Fabric 1.15.2?
- Have you tested with other mods? (Simply pick a random mod and try if Minecraft can load)

**Comment by KXIIIS** [comment]
- Yes, I can run Minecraft 1.15.2 without mods.
- Yes, I can run Fabric 1.15.2 if I remove this mod.
- Yes, I have tested it with other mods, but the game still doesn't load even with other mods. 

I feel bad because I don't have a lot of detail to give you and I'm not sure if this is happening because of something I did.

**Comment by anhcraft** [comment]
So, you can still run Fabric if have no mods at all? It seems serious as I've never seen this issue before.
Can you record a video? You should show these things:
- Your mods folder
- The launcher
- The logs 
When the game does not load anymore, wait about 30 seconds.
Contact me via Discord if you want to keep it private: anhcraft#1646

**Comment by KXIIIS** [comment]
Okay, I will PM you on Discord :)
